/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.Control.Persona;
import javax.swing.JOptionPane;
import Negocio.Modelo.Agenda;

/**
 *
 * @author vgremlin
 */
public class InterfazFormulario extends javax.swing.JFrame {

    /**
     * Creates new form InterfazFormulario
     */
    public InterfazFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        JLIdentificacion = new javax.swing.JLabel();
        JLNombre = new javax.swing.JLabel();
        JLApellidos = new javax.swing.JLabel();
        JLFechaNac = new javax.swing.JLabel();
        JLPaisNac = new javax.swing.JLabel();
        JLDeptoNac = new javax.swing.JLabel();
        JLCiudadNac = new javax.swing.JLabel();
        JLTelefono = new javax.swing.JLabel();
        JLCelular = new javax.swing.JLabel();
        ButtonNuevo = new javax.swing.JButton();
        ButtonGrabar = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        ButtonBuscar = new javax.swing.JButton();
        ButtonListar = new javax.swing.JButton();
        TXTIdentificacion = new javax.swing.JTextField();
        TXTNombres = new javax.swing.JTextField();
        TXTApellidos = new javax.swing.JTextField();
        TXTTelefono = new javax.swing.JTextField();
        TXTCelular = new javax.swing.JTextField();
        TXTFechaNac = new javax.swing.JTextField();
        ChoicePais = new java.awt.Choice();
        ChoiceDepto = new java.awt.Choice();
        ChoiceCiudad = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORMULARIO");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Menu.selectionBackground"));

        JLIdentificacion.setText("Numero de identificacion");

        JLNombre.setText("Nombres");

        JLApellidos.setText("Apellidos");

        JLFechaNac.setText("Fecha de Nacimiento");

        JLPaisNac.setText("Pais");

        JLDeptoNac.setText("Depto");

        JLCiudadNac.setText("Ciudad");

        JLTelefono.setText("Telefono casa");

        JLCelular.setText("Celular");

        ButtonNuevo.setText("Nuevo");
        ButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevoActionPerformed(evt);
            }
        });

        ButtonGrabar.setText("Grabar");
        ButtonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGrabarActionPerformed(evt);
            }
        });

        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        ButtonListar.setText("Listar");
        ButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarActionPerformed(evt);
            }
        });

        TXTNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNombresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLFechaNac)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLTelefono)
                                            .addComponent(JLCelular)
                                            .addComponent(JLNombre))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TXTCelular)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TXTTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(ChoicePais, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(JLDeptoNac)
                                                        .addGap(2, 2, 2)
                                                        .addComponent(ChoiceDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 31, Short.MAX_VALUE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLPaisNac)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JLCiudadNac)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChoiceCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtonNuevo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonGrabar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonEliminar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonListar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLIdentificacion)
                                            .addComponent(JLApellidos))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TXTNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                                            .addComponent(TXTApellidos)
                                            .addComponent(TXTIdentificacion)
                                            .addComponent(TXTFechaNac))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(170, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLIdentificacion)
                    .addComponent(TXTIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNombre)
                    .addComponent(TXTNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLApellidos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLFechaNac)
                    .addComponent(TXTFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JLPaisNac)
                                .addComponent(JLDeptoNac))
                            .addComponent(ChoiceDepto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLCiudadNac)
                            .addComponent(ChoicePais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLTelefono)
                            .addComponent(TXTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLCelular)
                            .addComponent(TXTCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonNuevo)
                            .addComponent(ButtonGrabar)
                            .addComponent(ButtonEliminar)
                            .addComponent(ButtonBuscar)
                            .addComponent(ButtonListar))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ChoiceCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuevoActionPerformed
        TXTIdentificacion.setText( "" ) ;
        TXTNombres.setText( "" ) ; 
        TXTApellidos.setText( "" ) ;
        TXTCelular.setText( "" ) ;
        TXTFechaNac.setText( "" ) ;
        TXTTelefono.setText( "" ) ;
    }//GEN-LAST:event_ButtonNuevoActionPerformed

    private void TXTNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombresActionPerformed
    
    Agenda agenda=new Agenda();
    Persona persona= new Persona();
    String identificacion, nombres, apellidos, fechaNac , telefono, celular;
    //Persona persona = new Persona(identificacion, nombres, apellidos, fechaNac , telefono, celular);
    
    private void ButtonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGrabarActionPerformed
        //String identificacion, nombres, apellidos, fechaNac , telefono, celular;
        identificacion=TXTIdentificacion.getText();
        nombres=TXTNombres.getText();
        apellidos=TXTApellidos.getText();
        fechaNac=TXTFechaNac.getText();
        telefono=TXTTelefono.getText();
        celular=TXTCelular.getText();
        Persona persona = new Persona(identificacion, nombres, apellidos, fechaNac,telefono, celular);
        agenda.GuardarPersona(persona);
         //JOptionPane.showMessageDialog(null, identificacion);
    }//GEN-LAST:event_ButtonGrabarActionPerformed

    private void ButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarActionPerformed
        JOptionPane.showMessageDialog(null, agenda.MostrarAgenda());
    }//GEN-LAST:event_ButtonListarActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        identificacion=TXTIdentificacion.getText();
        nombres=TXTNombres.getText();
        apellidos=TXTApellidos.getText();
        fechaNac=TXTFechaNac.getText();
        telefono=TXTTelefono.getText();
        celular=TXTCelular.getText();
        String seleccion = null;
       //Persona persona = new Persona(identificacion, nombres, apellidos, fechaNac,telefono, celular);
        agenda.Buscar(seleccion, identificacion);
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        identificacion=TXTIdentificacion.getText();
        nombres=TXTNombres.getText();
        apellidos=TXTApellidos.getText();
        fechaNac=TXTFechaNac.getText();
        telefono=TXTTelefono.getText();
        celular=TXTCelular.getText();
        String seleccion = null;
        agenda.Buscar(seleccion, identificacion);
    }//GEN-LAST:event_ButtonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonGrabar;
    private javax.swing.JButton ButtonListar;
    private javax.swing.JButton ButtonNuevo;
    private java.awt.Choice ChoiceCiudad;
    private java.awt.Choice ChoiceDepto;
    private java.awt.Choice ChoicePais;
    private javax.swing.JLabel JLApellidos;
    private javax.swing.JLabel JLCelular;
    private javax.swing.JLabel JLCiudadNac;
    private javax.swing.JLabel JLDeptoNac;
    private javax.swing.JLabel JLFechaNac;
    private javax.swing.JLabel JLIdentificacion;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JLabel JLPaisNac;
    private javax.swing.JLabel JLTelefono;
    private javax.swing.JTextField TXTApellidos;
    private javax.swing.JTextField TXTCelular;
    private javax.swing.JTextField TXTFechaNac;
    private javax.swing.JTextField TXTIdentificacion;
    private javax.swing.JTextField TXTNombres;
    private javax.swing.JTextField TXTTelefono;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    // End of variables declaration//GEN-END:variables
}
